# Generated by Django 3.2.18 on 2023-04-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20230412_0051'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetag',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_tags', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='issuetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_tags', to='tags.tag'),
        ),
    ]
