# Generated by Django 3.2.18 on 2023-05-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificationreceiver',
            table='notification_receivers',
        ),
    ]
