# Generated by Django 3.2.18 on 2023-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
