# Generated by Django 3.2.18 on 2023-04-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='follows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
