# Generated by Django 3.2.18 on 2023-04-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20230420_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewissues',
            old_name='reviewer',
            new_name='reviewed',
        ),
        migrations.AlterField(
            model_name='reviewissues',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
