# Generated by Django 3.2.18 on 2023-04-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('issues', '0002_alter_reviewissues_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptissues',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopt_issues', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='adoptissues',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopt_issues', to='users.user'),
        ),
        migrations.AlterField(
            model_name='likeissues',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_issues', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='likeissues',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_issues', to='users.user'),
        ),
        migrations.AlterField(
            model_name='reviewissues',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_issues', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='reviewissues',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_issues_reviewer', to='users.user'),
        ),
        migrations.AlterField(
            model_name='reviewissues',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_issues_user', to='users.user'),
        ),
    ]
