# Generated by Django 3.2.18 on 2023-05-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
        ('users', '0002_blacklist'),
        ('issues', '0003_auto_20230423_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.CharField(max_length=3071, null=True)),
                ('anonymous', models.IntegerField(null=True)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_chapter', to='chapters.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_draft', to='users.user')),
            ],
            options={
                'db_table': 'user_drafts',
            },
        ),
    ]
