# Generated by Django 3.2.18 on 2023-04-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_privilege_user'),
        ('issues', '0004_auto_20230412_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewissues',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_review_issues', to='users.user'),
        ),
        migrations.AlterField(
            model_name='reviewissues',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review_issues', to='users.user'),
        ),
    ]
