# Generated by Django 3.2.18 on 2023-05-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_userdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAssociations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associate_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associate_issues_as_to', to='issues.issue')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associate_issues_as_from', to='issues.issue')),
            ],
            options={
                'db_table': 'issue_associations',
            },
        ),
    ]
