# Generated by Django 3.2.18 on 2023-04-11 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_privilege_user'),
        ('issues', '0005_auto_20230412_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='counselor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_issues', to='users.user'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_issues', to='users.user'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_issues', to='users.user'),
        ),
    ]
