# Generated by Django 3.2.18 on 2023-05-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issueassociations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='counsel_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='review_at',
            field=models.DateTimeField(null=True),
        ),
    ]
