# Generated by Django 3.2.18 on 2023-05-22 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklist'),
        ('issues', '0006_auto_20230522_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueApiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_api_call_history', to='issues.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_api_call_history', to='users.user')),
            ],
            options={
                'db_table': 'issue_api_calls',
            },
        ),
    ]
