class GlobalCode:
    SUCCESS = 0
    SYSTEM_FAILED = 1


class UserRole:
    ALL_USERS = [0, 1, 2]
    ADMIN_ONLY = [2, ]


class YearErrorCode:
    YEAR_SAVE_FAILED = 101
    YEAR_DOES_NOT_EXIST = 102
    YEAR_DELETE_FAILED = 103


class UserErrorCode:
    USER_NOT_FOUND = 201
    INCORRECT_PASSWORD = 202
    EXPIRED_JWT = 203
    INVALID_JWT = 204
    USER_SAVE_FAILED = 205
    USER_FROZEN = 206
    PERMISSION_DENIED = 207


class IssueErrorCode:
    ISSUE_NOT_FOUND = 301
    ISSUE_DELETE_FAILED = 302
    ISSUE_SAVED_FAILED = 303
    REVIEW_ISSUE_QUERY_FAILED = 304
    ADOPT_ISSUE_QUERY_FAILED = 305
    FOLLOW_ISSUE_QUERY_FAILED = 306
    ASK_ISSUE_QUERY_FAILED = 307


class OtherErrorCode:
    UNEXPECTED_JSON_FORMAT = 901


class SubjectErrorCode:
    SUBJECT_SAVE_FAILED = 301
    SUBJECT_DOES_NOT_EXIST = 302
    SUBJECT_DELETE_FAILED = 303
    SUBJECT_LIST_UPDATE_FAILED = 304


class ChapterErrorCode:
    CHAPTER_SAVE_FAILED = 401
    CHAPTER_DOES_NOT_EXIST = 402
    CHAPTER_DELETE_FAILED = 403


class TagErrorCode:
    TAG_SAVE_FAILED = 501
    TAG_DOES_NOT_EXIST = 502
    TAG_DELETE_FAILED = 503
